/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "AuthenticationService_constants.h"

namespace aroma { namespace banana { namespace thrift { namespace authentication { namespace service {

const AuthenticationServiceConstants g_AuthenticationService_constants;

AuthenticationServiceConstants::AuthenticationServiceConstants() {
  API_VERSION = 1.4;

  SERVICE_PORT = 6001;

  PRODUCTION_ENDPOINT.hostname = "authentication-srv.banana.aroma.tech";
   ::aroma::banana::thrift::endpoint::int tmp32;
  tmp32 = 6001;

  PRODUCTION_ENDPOINT.port = tmp32;

  BETA_ENDPOINT.hostname = "authentication-srv.beta.banana.aroma.tech";
   ::aroma::banana::thrift::endpoint::int tmp33;
  tmp33 = 6001;

  BETA_ENDPOINT.port = tmp33;

}

}}}}} // namespace

