/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Authentication_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>



int _kSeverityValues[] = {
  Severity::INFORMATIONAL,
  Severity::WARNING,
  Severity::ERROR
};
const char* _kSeverityNames[] = {
  "INFORMATIONAL",
  "WARNING",
  "ERROR"
};
const std::map<int, const char*> _Severity_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(3, _kSeverityValues, _kSeverityNames), ::apache::thrift::TEnumIterator(-1, NULL, NULL));


