/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Email_constants.h"

namespace aroma { namespace thrift { namespace email {

const EmailConstants g_Email_constants;

EmailConstants::EmailConstants() {
}

}}} // namespace

