/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef MessageService_TYPES_H
#define MessageService_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/TBase.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <thrift/stdcxx.h>
#include "Authentication_types.h"
#include "Aroma_types.h"
#include "Channels_types.h"
#include "Endpoint_types.h"
#include "Events_types.h"
#include "Exceptions_types.h"
#include "ApplicationService_types.h"
#include "AromaService_types.h"


namespace aroma { namespace thrift { namespace message { namespace service {

typedef  ::tech::aroma::thrift::int int;

typedef  ::tech::aroma::thrift::long long;

typedef  ::tech::aroma::thrift::timestamp timestamp;

typedef class  ::aroma::thrift::authentication::ApplicationToken ApplicationToken;

typedef class  ::aroma::thrift::authentication::AuthenticationToken AuthenticationToken;

typedef class  ::aroma::thrift::authentication::UserToken UserToken;

typedef class  ::tech::aroma::thrift::Application Application;

typedef  ::tech::aroma::thrift::Urgency::type Urgency;

typedef class  ::aroma::thrift::events::Event Event;

typedef class  ::aroma::thrift::exceptions::AccountAlreadyExistsException AccountAlreadyExistsException;

typedef class  ::aroma::thrift::exceptions::InvalidArgumentException InvalidArgumentException;

typedef class  ::aroma::thrift::exceptions::InvalidCredentialsException InvalidCredentialsException;

typedef class  ::aroma::thrift::exceptions::InvalidTokenException InvalidTokenException;

typedef class  ::aroma::thrift::exceptions::OperationFailedException OperationFailedException;

typedef class  ::aroma::thrift::exceptions::ApplicationAlreadyRegisteredException ApplicationAlreadyRegisteredException;

typedef class  ::aroma::thrift::exceptions::ApplicationDoesNotExistException ApplicationDoesNotExistException;

typedef class  ::aroma::thrift::exceptions::CustomChannelUnreachableException CustomChannelUnreachableException;

typedef class  ::aroma::thrift::exceptions::ChannelDoesNotExistException ChannelDoesNotExistException;

typedef class  ::aroma::thrift::exceptions::UnauthorizedException UnauthorizedException;

typedef class  ::aroma::thrift::application::service::SendMessageRequest SendMessageRequest;

typedef class  ::aroma::thrift::application::service::SendMessageResponse SendMessageResponse;

typedef class  ::aroma::thrift::service::DeleteMessageRequest DeleteMessageRequest;

typedef class  ::aroma::thrift::service::DeleteMessageResponse DeleteMessageResponse;

typedef class  ::aroma::thrift::service::DismissMessageRequest DismissMessageRequest;

typedef class  ::aroma::thrift::service::DismissMessageResponse DismissMessageResponse;

typedef class  ::aroma::thrift::service::GetApplicationMessagesRequest GetApplicationMessagesRequest;

typedef class  ::aroma::thrift::service::GetApplicationMessagesResponse GetApplicationMessagesResponse;

typedef class  ::aroma::thrift::service::GetInboxRequest GetInboxRequest;

typedef class  ::aroma::thrift::service::GetInboxResponse GetInboxResponse;

typedef class  ::aroma::thrift::service::GetFullMessageRequest GetFullMessageRequest;

typedef class  ::aroma::thrift::service::GetFullMessageResponse GetFullMessageResponse;

}}}} // namespace

#endif
