/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "NotificationService_constants.h"

namespace aroma { namespace banana { namespace thrift { namespace notification { namespace service {

const NotificationServiceConstants g_NotificationService_constants;

NotificationServiceConstants::NotificationServiceConstants() {
  API_VERSION = 1.5;

  SERVICE_PORT = 9009;

  PRODUCTION_ENDPOINT.hostname = "notification-srv.banana.aroma.tech";
   ::aroma::banana::thrift::endpoint::int tmp4;
  tmp4 = 9009;

  PRODUCTION_ENDPOINT.port = tmp4;

  BETA_ENDPOINT.hostname = "notification-srv.beta.banana.aroma.tech";
   ::aroma::banana::thrift::endpoint::int tmp5;
  tmp5 = 9009;

  BETA_ENDPOINT.port = tmp5;

}

}}}}} // namespace

