/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"
#import "TBase.h"
#import "TAsyncTransport.h"
#import "TProtocolFactory.h"
#import "TBaseClient.h"

#import "Banana.h"

enum BananaAuthentication_Role {
  Role_DEV = 1,
  Role_OWNER = 2
};

typedef int32_t BananaAuthentication_int;

typedef int64_t BananaAuthentication_long;

typedef int64_t BananaAuthentication_timestamp;

@interface BananaAuthentication_Developer : NSObject <TBase, NSCoding> {
  NSString * __email;
  NSString * __name;
  NSString * __username;
  int __role;

  BOOL __email_isset;
  BOOL __name_isset;
  BOOL __username_isset;
  BOOL __role_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=email, setter=setEmail:) NSString * email;
@property (nonatomic, retain, getter=name, setter=setName:) NSString * name;
@property (nonatomic, retain, getter=username, setter=setUsername:) NSString * username;
@property (nonatomic, getter=role, setter=setRole:) int role;
#endif

- (id) init;
- (id) initWithEmail: (NSString *) email name: (NSString *) name username: (NSString *) username role: (int) role;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) email;
- (void) setEmail: (NSString *) email;
#endif
- (BOOL) emailIsSet;

#if !__has_feature(objc_arc)
- (NSString *) name;
- (void) setName: (NSString *) name;
#endif
- (BOOL) nameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) username;
- (void) setUsername: (NSString *) username;
#endif
- (BOOL) usernameIsSet;

#if !__has_feature(objc_arc)
- (int) role;
- (void) setRole: (int) role;
#endif
- (BOOL) roleIsSet;

@end

@interface BananaAuthentication_AuthenticationConstants : NSObject {
}
@end
