/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"
#import "TBase.h"
#import "TAsyncTransport.h"
#import "TProtocolFactory.h"
#import "TBaseClient.h"

#import "Banana.h"

enum BananaAuthentication_Role {
  Role_DEV = 1,
  Role_OWNER = 2
};

typedef int32_t BananaAuthentication_int;

typedef int64_t BananaAuthentication_long;

typedef int64_t BananaAuthentication_timestamp;

@interface BananaAuthentication_Developer : NSObject <TBase, NSCoding> {
  NSString * __email;
  NSString * __name;
  NSString * __username;
  int __role;

  BOOL __email_isset;
  BOOL __name_isset;
  BOOL __username_isset;
  BOOL __role_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=email, setter=setEmail:) NSString * email;
@property (nonatomic, retain, getter=name, setter=setName:) NSString * name;
@property (nonatomic, retain, getter=username, setter=setUsername:) NSString * username;
@property (nonatomic, getter=role, setter=setRole:) int role;
#endif

- (id) init;
- (id) initWithEmail: (NSString *) email name: (NSString *) name username: (NSString *) username role: (int) role;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) email;
- (void) setEmail: (NSString *) email;
#endif
- (BOOL) emailIsSet;

#if !__has_feature(objc_arc)
- (NSString *) name;
- (void) setName: (NSString *) name;
#endif
- (BOOL) nameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) username;
- (void) setUsername: (NSString *) username;
#endif
- (BOOL) usernameIsSet;

#if !__has_feature(objc_arc)
- (int) role;
- (void) setRole: (int) role;
#endif
- (BOOL) roleIsSet;

@end

@interface BananaAuthentication_ServiceToken : NSObject <TBase, NSCoding> {
  NSString * __id;
  NSString * __serviceName;
  NSString * __organization;
  BananaAuthentication_timestamp __timeOfExpiration;

  BOOL __id_isset;
  BOOL __serviceName_isset;
  BOOL __organization_isset;
  BOOL __timeOfExpiration_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=id, setter=setId:) NSString * id;
@property (nonatomic, retain, getter=serviceName, setter=setServiceName:) NSString * serviceName;
@property (nonatomic, retain, getter=organization, setter=setOrganization:) NSString * organization;
@property (nonatomic, getter=timeOfExpiration, setter=setTimeOfExpiration:) BananaAuthentication_timestamp timeOfExpiration;
#endif

- (id) init;
- (id) initWithId: (NSString *) id serviceName: (NSString *) serviceName organization: (NSString *) organization timeOfExpiration: (BananaAuthentication_timestamp) timeOfExpiration;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) id;
- (void) setId: (NSString *) id;
#endif
- (BOOL) idIsSet;

#if !__has_feature(objc_arc)
- (NSString *) serviceName;
- (void) setServiceName: (NSString *) serviceName;
#endif
- (BOOL) serviceNameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) organization;
- (void) setOrganization: (NSString *) organization;
#endif
- (BOOL) organizationIsSet;

#if !__has_feature(objc_arc)
- (BananaAuthentication_timestamp) timeOfExpiration;
- (void) setTimeOfExpiration: (BananaAuthentication_timestamp) timeOfExpiration;
#endif
- (BOOL) timeOfExpirationIsSet;

@end

@interface BananaAuthentication_DeveloperToken : NSObject <TBase, NSCoding> {
  NSString * __id;
  NSString * __oauthProvider;
  BananaAuthentication_timestamp __timeOfExpiration;
  NSString * __organization;

  BOOL __id_isset;
  BOOL __oauthProvider_isset;
  BOOL __timeOfExpiration_isset;
  BOOL __organization_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=id, setter=setId:) NSString * id;
@property (nonatomic, retain, getter=oauthProvider, setter=setOauthProvider:) NSString * oauthProvider;
@property (nonatomic, getter=timeOfExpiration, setter=setTimeOfExpiration:) BananaAuthentication_timestamp timeOfExpiration;
@property (nonatomic, retain, getter=organization, setter=setOrganization:) NSString * organization;
#endif

- (id) init;
- (id) initWithId: (NSString *) id oauthProvider: (NSString *) oauthProvider timeOfExpiration: (BananaAuthentication_timestamp) timeOfExpiration organization: (NSString *) organization;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) id;
- (void) setId: (NSString *) id;
#endif
- (BOOL) idIsSet;

#if !__has_feature(objc_arc)
- (NSString *) oauthProvider;
- (void) setOauthProvider: (NSString *) oauthProvider;
#endif
- (BOOL) oauthProviderIsSet;

#if !__has_feature(objc_arc)
- (BananaAuthentication_timestamp) timeOfExpiration;
- (void) setTimeOfExpiration: (BananaAuthentication_timestamp) timeOfExpiration;
#endif
- (BOOL) timeOfExpirationIsSet;

#if !__has_feature(objc_arc)
- (NSString *) organization;
- (void) setOrganization: (NSString *) organization;
#endif
- (BOOL) organizationIsSet;

@end

@interface BananaAuthentication_GithubToken : NSObject <TBase, NSCoding> {
  NSString * __username;
  NSString * __email;
  NSString * __oauthToken;

  BOOL __username_isset;
  BOOL __email_isset;
  BOOL __oauthToken_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=username, setter=setUsername:) NSString * username;
@property (nonatomic, retain, getter=email, setter=setEmail:) NSString * email;
@property (nonatomic, retain, getter=oauthToken, setter=setOauthToken:) NSString * oauthToken;
#endif

- (id) init;
- (id) initWithUsername: (NSString *) username email: (NSString *) email oauthToken: (NSString *) oauthToken;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) username;
- (void) setUsername: (NSString *) username;
#endif
- (BOOL) usernameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) email;
- (void) setEmail: (NSString *) email;
#endif
- (BOOL) emailIsSet;

#if !__has_feature(objc_arc)
- (NSString *) oauthToken;
- (void) setOauthToken: (NSString *) oauthToken;
#endif
- (BOOL) oauthTokenIsSet;

@end

@interface BananaAuthentication_OauthToken : NSObject <TBase, NSCoding> {
  BananaAuthentication_GithubToken * __githubToken;

  BOOL __githubToken_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=githubToken, setter=setGithubToken:) BananaAuthentication_GithubToken * githubToken;
#endif

- (id) init;
- (id) initWithGithubToken: (BananaAuthentication_GithubToken *) githubToken;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (BananaAuthentication_GithubToken *) githubToken;
- (void) setGithubToken: (BananaAuthentication_GithubToken *) githubToken;
#endif
- (BOOL) githubTokenIsSet;

@end

@interface BananaAuthentication_AuthenticationConstants : NSObject {
}
@end
