//
// Autogenerated by Thrift Compiler (0.9.3)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


SERVICE_PORT = 7005;
PRODUCTION_ENDPOINT = new TcpEndpoint({
'hostname' : 'application-srv.banana.aroma.tech','port' : 7005});
BETA_ENDPOINT = new TcpEndpoint({
'hostname' : 'application-srv.beta.banana.aroma.tech','port' : 7005});
