//
// Autogenerated by Thrift Compiler (0.11.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


//HELPER FUNCTIONS AND STRUCTURES

CustomAromaChannel_ping_args = function(args) {
};
CustomAromaChannel_ping_args.prototype = {};
CustomAromaChannel_ping_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

CustomAromaChannel_ping_args.prototype.write = function(output) {
  output.writeStructBegin('CustomAromaChannel_ping_args');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

CustomAromaChannel_ping_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = args.success;
    }
  }
};
CustomAromaChannel_ping_result.prototype = {};
CustomAromaChannel_ping_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.I32) {
        this.success = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

CustomAromaChannel_ping_result.prototype.write = function(output) {
  output.writeStructBegin('CustomAromaChannel_ping_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.I32, 0);
    output.writeI32(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

CustomAromaChannel_receiveMessage_args = function(args) {
  this.request = null;
  if (args) {
    if (args.request !== undefined && args.request !== null) {
      this.request = new ReceiveMessageRequest(args.request);
    }
  }
};
CustomAromaChannel_receiveMessage_args.prototype = {};
CustomAromaChannel_receiveMessage_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.request = new ReceiveMessageRequest();
        this.request.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

CustomAromaChannel_receiveMessage_args.prototype.write = function(output) {
  output.writeStructBegin('CustomAromaChannel_receiveMessage_args');
  if (this.request !== null && this.request !== undefined) {
    output.writeFieldBegin('request', Thrift.Type.STRUCT, 1);
    this.request.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

CustomAromaChannel_receiveMessage_result = function(args) {
};
CustomAromaChannel_receiveMessage_result.prototype = {};
CustomAromaChannel_receiveMessage_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

CustomAromaChannel_receiveMessage_result.prototype.write = function(output) {
  output.writeStructBegin('CustomAromaChannel_receiveMessage_result');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

CustomAromaChannelClient = function(input, output) {
    this.input = input;
    this.output = (!output) ? input : output;
    this.seqid = 0;
};
CustomAromaChannelClient.prototype = {};
CustomAromaChannelClient.prototype.ping = function(callback) {
  this.send_ping(callback); 
  if (!callback) {
    return this.recv_ping();
  }
};

CustomAromaChannelClient.prototype.send_ping = function(callback) {
  this.output.writeMessageBegin('ping', Thrift.MessageType.CALL, this.seqid);
  var args = new CustomAromaChannel_ping_args();
  args.write(this.output);
  this.output.writeMessageEnd();
  if (callback) {
    var self = this;
    this.output.getTransport().flush(true, function() {
      var result = null;
      try {
        result = self.recv_ping();
      } catch (e) {
        result = e;
      }
      callback(result);
    });
  } else {
    return this.output.getTransport().flush();
  }
};

CustomAromaChannelClient.prototype.recv_ping = function() {
  var ret = this.input.readMessageBegin();
  var fname = ret.fname;
  var mtype = ret.mtype;
  var rseqid = ret.rseqid;
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(this.input);
    this.input.readMessageEnd();
    throw x;
  }
  var result = new CustomAromaChannel_ping_result();
  result.read(this.input);
  this.input.readMessageEnd();

  if (null !== result.success) {
    return result.success;
  }
  throw 'ping failed: unknown result';
};
CustomAromaChannelClient.prototype.receiveMessage = function(request, callback) {
  this.send_receiveMessage(request, callback); 
};

CustomAromaChannelClient.prototype.send_receiveMessage = function(request, callback) {
  this.output.writeMessageBegin('receiveMessage', Thrift.MessageType.ONEWAY, this.seqid);
  var params = {
    request: request
  };
  var args = new CustomAromaChannel_receiveMessage_args(params);
  args.write(this.output);
  this.output.writeMessageEnd();
  if (callback) {
    this.output.getTransport().flush(true, null);
  } else {
    return this.output.getTransport().flush();
  }
};
